# Generated by Django 3.1.7 on 2021-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
